---
- name: Install Git
  apt: name=git update_cache=yes state=present
  become: yes
  become_user: root
  tags: setup

- name: Update npm
  npm: name=npm version=3.8.7 global=yes
  become: yes
  become_user: root
  tags: setup

- include: setup_yarn.yml
  tags: yarn setup

- name: Install Browserify
  command: yarn global add browserify@13.0.0
  become: yes
  become_user: root
  tags: setup
