---
- name: Get install script
  get_url:
    url: https://yarnpkg.com/install.sh
    dest: /tmp/install_yarn.sh
    mode: u+x

- name: Install Yarn
  shell: /tmp/install_yarn.sh --version {{ yarn_version }}
  environment:
    PATH: "{{ node_path }}:{{ ansible_env.PATH }}"
  args:
    executable: /bin/bash
