---
- name: Creates CPDB directory for deployment
  sudo: yes
  file: path=/CPDB state=directory owner=ansible

- name: Pull code from frontend repo
  git: repo= dest=/CPDB/ key_file=/home/ansible/.ssh/github accept_hostkey=True version={{ branch }}

- name: Install npm packages
  command: npm install
    chdir=/CPDB/

- name: Install gulp cli
  npm: name=gulp-cli version=1.2.1 global=yes
  sudo: yes

- name: Clean static root
  sudo: yes
  file: path=/www/static/dist state=absent

- name: Create static root
  sudo: yes
  file: path=/www/static/dist state=directory owner=ansible

- name: Build everything
  command: npm run build
    chdir=/CPDB/
