---
- name: Creates CPDB directory for deployment
  sudo: yes
  file: path=/CPDB state=directory owner=ansible

- name: Pull code from frontend repo
  git: repo= dest=/CPDB/ key_file=/home/ansible/.ssh/github accept_hostkey=True version={{ branch }}

- name: Install npm packages
  npm: path=/CPDB

- name: Build js bundle
  command: npm run build
    chdir=/CPDB/

- name: Create static root
  sudo: yes
  file: path=/www/static/dist state=directory owner=ansible

- name: Copy index.html to static root
  command: cp /CPDB/index.html /www/static/index.html

- name: Copy bundle.js to static root
  command: cp /CPDB/bundle.js /www/static/dist/bundle.js
