---
- name: Creates CPDB directory for deployment
  become: yes
  become_user: root
  file: path=/CPDB state=directory owner={{ deploy_user }} group={{ deploy_group }}
  tags: setup

- name: Pull code from frontend repo
  git: repo= dest={{ application_root_path }} accept_hostkey=True version={{ branch }}
  tags: deploy

- name : Install packages based on package.json.
  npm: path={{ application_root_path }} production=yes
  tags: deploy

- name: Install gulp cli
  npm: name=gulp-cli version=1.2.1 global=yes
  become: yes
  become_user: root
  tags: setup

- name: Create static root
  become: yes
  become_user: root
  file: path=/www/static/dist state=directory owner={{ deploy_user }} group={{ deploy_group }}
  tags: setup

- name: Build everything
  command: npm run build
    chdir={{ application_root_path }}
  tags: deploy
