---
- name: Creates CPDB directory for deployment
  become: yes
  become_user: root
  file: path=/CPDB state=directory owner={{ deploy_user }} group={{ deploy_group }}
  tags: setup

- name: Pull code from frontend repo
  git: repo=
    dest={{ application_root_path }}
    accept_hostkey=True
    version={{ branch }}
    key_file=***REMOVED***
    force=yes
  tags: deploy

- name : Install packages based on package.json.
  command: yarn
    chdir={{ application_root_path }}
  tags: deploy

- name: Install gulp
  command: yarn global add gulp@3.9.1
  become: yes
  become_user: root
  tags: setup

- name: Install gulp cli
  command: yarn global add gulp-cli@1.2.1
  become: yes
  become_user: root
  tags: setup

- name: Clean static root
  become: yes
  become_user: root
  file: path=/www/static/dist state=absent
  tags: deploy

- name: Create static root
  become: yes
  become_user: root
  file: path=/www/static/dist state=directory owner={{ deploy_user }} group={{ deploy_group }}
  tags: deploy

- name: Build everything
  command: yarn build
    chdir={{ application_root_path }}
  tags: deploy
