version: 2
jobs:

  test:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run: pwd
      - run: yarn install
      - run: yarn lint
      - run: yarn cover-circle
      - run: cat lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run: yarn live-test
      - store_artifacts:
          path: /home/deploy/errorShots

  deploy:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: az storage blob delete-batch -s fstatic --account-name cpdbv21777
      - run: azcopy --source ./dist/ --destination https://cpdbv21777.blob.core.windows.net/fstatic --dest-key $STORAGE_KEY --recursive

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: staging
