version: 2
jobs:

  test:
    docker:
      - image: nhanbui/cpdbv2_frontend:0.0.3
    environment:
      NODE_ENV: development
      ERROR_SCREENSHOT_DIR: /home/ubuntu/CPDBv2_frontend/errorShots
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn cover-circle
      - run: yarn live-test
      - run: cat lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run:
          name: Gather error screenshots as artifacts
          command: if [ -d $ERROR_SCREENSHOT_DIR ]; then cp -r $ERROR_SCREENSHOT_DIR $CIRCLE_ARTIFACTS; fi

  deploy:
    docker:
      - image: nhanbui/cpdbv2_frontend:0.0.3
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - run: pip install --upgrade pyOpenSSL
      - run: bin/circle-deploy-staging

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: staging
