version: 2
jobs:

  test:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-node-modules-{{ checksum "package.json" }}-
            - v2-node-modules-
      - run: yarn
      - run: yarn lint
      - run: yarn cover
      - run: yarn cover-report
      - run: yarn live-test
      - store_artifacts:
          path: /home/deploy/errorShots
      - save_cache:
          key: v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/deploy/project/node_modules"

  deploy:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-node-modules-{{ checksum "package.json" }}-
            - v2-node-modules-
      - run: yarn
      - run:
          name: Build assets
          command: |
            if [ $CIRCLE_BRANCH == "master" ]
            then
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_PROD_ACCOUNT_NAME
              yarn build
            else
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_STAGING_ACCOUNT_NAME
              yarn build-staging
            fi
      - run:
          name: Build desktop-frontend image
          command: docker build -t cpdbdev/desktop-frontend:$(cat VERSION) .
      - run:
          name: Login to Docker hub
          command: docker login -u cpdbdev -p $DOCKER_PASSWORD
      - run:
          name: Upload image
          command: docker push cpdbdev/desktop-frontend:$(cat VERSION)
      - run:
          name: Apply deployment
          command: |
            echo $KUBECONFIG_JSON | /home/deploy/.kube/config.json
            sed -e "s/\${IMAGE_TAG}/$(cat VERSION)/" desktop-frontend.yml | kubectl --kubeconfig /home/deploy/.kube/config.json apply -f -

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - staging
                - master
