version: 2
jobs:

  test:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-node-modules-{{ checksum "package.json" }}-
            - v2-node-modules-
      - run: yarn
      - run: yarn lint
      - run: yarn cover
      - run: yarn cover-report
      - run: yarn live-test
      - store_artifacts:
          path: /home/deploy/errorShots
      - save_cache:
          key: v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/deploy/project/node_modules"

  deploy:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-node-modules-{{ checksum "package.json" }}-
            - v2-node-modules-
      - run: yarn
      - run:
          name: Build assets
          command: |
            if [ $CIRCLE_BRANCH == "master" ]
            then
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_PROD_ACCOUNT_NAME
              yarn build
            else
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_STAGING_ACCOUNT_NAME
              yarn build-staging
            fi
      - run:
          name: List open files
          command: lsof | grep /home/deploy/project
      - run:
          name: Copy all dist files to Azure blob storage
          command: |
            if [ $CIRCLE_BRANCH == "master" ]
            then
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_PROD_ACCOUNT_NAME
              export AZURE_STORAGE_ACCOUNT_KEY=$AZURE_STORAGE_PROD_ACCOUNT_KEY
            else
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_STAGING_ACCOUNT_NAME
              export AZURE_STORAGE_ACCOUNT_KEY=$AZURE_STORAGE_STAGING_ACCOUNT_KEY
            fi && echo $AZURE_STORAGE_ACCOUNT_NAME && echo $AZURE_STORAGE_ACCOUNT_KEY && echo $AZURE_STATICFILES_CONTAINER && \
            azcopy \
              --source /home/deploy/project/dist \
              --destination https://$AZURE_STORAGE_ACCOUNT_NAME.blob.core.windows.net/$AZURE_STATICFILES_CONTAINER \
              --dest-key $AZURE_STORAGE_ACCOUNT_KEY \
              --recursive \
              --quiet

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - staging
                - master
