version: 2
jobs:

  test:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-node-modules-{{ checksum "package.json" }}-
            - v2-node-modules-
      - run: yarn
      - run: yarn lint
      - run: yarn cover
      - run: yarn cover-report
      - run: yarn live-test
      - store_artifacts:
          path: /home/deploy/errorShots
      - save_cache:
          key: v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/deploy/project/node_modules"

  deploy:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-node-modules-{{ checksum "package.json" }}-
            - v2-node-modules-
      - run: yarn
      - run:
          name: Build assets
          command: |
            if [ $CIRCLE_BRANCH == "master" ]
            then
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_PROD_ACCOUNT_NAME
              yarn build
            else
              export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_STAGING_ACCOUNT_NAME
              yarn build-staging
            fi
      - run:
          name: Copy file index
          command: |
            azcopy \
              --source ./dist/index.html \
              --destination https://$AZURE_STORAGE_STAGING_ACCOUNT_NAME.blob.core.windows.net/$AZURE_STATICFILES_CONTAINER/index.html \
              --dest-key $AZURE_STORAGE_STAGING_ACCOUNT_KEY \
              --quiet
          when: always
      - run:
          name: Copy js file
          command: |
            export JSFILE=`ls dist | grep .js` && \
            azcopy \
              --source ./dist/$JSFILE \
              --destination https://$AZURE_STORAGE_STAGING_ACCOUNT_NAME.blob.core.windows.net/$AZURE_STATICFILES_CONTAINER/$JSFILE \
              --dest-key $AZURE_STORAGE_STAGING_ACCOUNT_KEY \
              --quiet
          when: always
      - run:
          name: Copy css file
          command: |
            export CSSFILE=`ls dist | grep .css` && \
            azcopy \
              --source ./dist/$CSSFILE \
              --destination https://$AZURE_STORAGE_STAGING_ACCOUNT_NAME.blob.core.windows.net/$AZURE_STATICFILES_CONTAINER/$CSSFILE \
              --dest-key $AZURE_STORAGE_STAGING_ACCOUNT_KEY \
              --quiet
          when: always
      - run:
          name: Copy fonts
          command: |
            azcopy \
              --source ./dist/fonts \
              --destination https://$AZURE_STORAGE_STAGING_ACCOUNT_NAME.blob.core.windows.net/$AZURE_STATICFILES_CONTAINER/fonts \
              --dest-key $AZURE_STORAGE_STAGING_ACCOUNT_KEY \
              --recursive \
              --quiet
          when: always
      - run:
          name: Copy img
          command: |
            azcopy \
              --source ./dist/img \
              --destination https://$AZURE_STORAGE_STAGING_ACCOUNT_NAME.blob.core.windows.net/$AZURE_STATICFILES_CONTAINER/img \
              --dest-key $AZURE_STORAGE_STAGING_ACCOUNT_KEY \
              --recursive \
              --quiet
          when: always

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - staging
                - master
