version: 2
jobs:

  test:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-node-modules-{{ checksum "package.json" }}-
            - v1-node-modules-
      - run: yarn
      - run: yarn lint
      - run: yarn cover-circle
      - run: cat lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run: yarn live-test
      - store_artifacts:
          path: /home/deploy/errorShots
      - save_cache:
          key: v1-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/deploy/node_modules"

  deploy:
    docker:
      - image: cpdbdev/cpdbv2_frontend:0.2.0
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-node-modules-{{ checksum "package.json" }}-
            - v1-node-modules-
      - run: yarn
      - run:
          name: Build assets
          command: |
            if [ $CIRCLE_BRANCH == "master" ]
            then
              yarn build
            else
              yarn build-staging
            fi
      - run:
          name: Copy all dist files to Azure blob storage
          command: |
            azcopy \
              --source ./dist \
              --destination https://$AZURE_STORAGE_ACCOUNT_NAME.blob.core.windows.net/$CONTAINER_PREFIX-$CIRCLE_BRANCH \
              --dest-key $AZURE_STORAGE_ACCOUNT_KEY \
              --recursive

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - staging
                - master
